name = "QPSReader"
uuid = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
version = "0.2.1"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
LazyArtifacts = "1.10"
julia = "1.10"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Logging", "SparseArrays", "Test"]
